### ISSUE TITLE
Modal window does not work on demo page

### ISSUE THREAD

**Issue by il-s** [cssninjaStudio/fresh#25]
As far as I understood, the modal window should appear when you click on **Log in**, but nothing happens. Apparently the **modal-trigger** handler got lost somewhere ...

**Comment by il-s** [comment]
Solution path:

add in src/js/libs/utils/utils.js
```
export function initModals() {
  let targets = document.querySelectorAll(".modal-trigger");
  if (typeof targets != "undefined" && targets != null) {
    for (var i = 0, len = targets.length; i < len; i++) {
        targets[i].addEventListener('click',  function (event) {
          console.log('click modal');
          var modalID = this.getAttribute('data-modal');
          document.querySelector('#' + modalID).classList.add('is-active');
        })
    }
  }

  targets = document.querySelectorAll(".modal-close");
  if (typeof targets != "undefined" && targets != null) {
    for (var i = 0, len = targets.length; i < len; i++) {
        targets[i].addEventListener('click',  function (event) {
          console.log('click modal close');
          this.closest('.modal').classList.remove('is-active');
        })
    }
  }
}
```

in js/main.js 
1. add initModals in import from ulils.js
2. add in document.onreadystatechange = function () {
```
...
const modals = initModals();
```
Enjoy)

**Comment by cssninjaStudio** [comment]
Hi, thanks for this contribution. Would you be kind to submit it as a PR? I'll review it and merge it then. Thanks!

**Comment by il-s** [comment]
There are still problems there:
1. **navbar** will overlap the close button
2. in modal mode, the **backtotop** button is again visible and active
3. **scrolling** continues when the modal is open

I do not yet have a solution to these questions, but I continue to think about it,

**Comment by cssninjaStudio** [comment]
You can submit the PR as is and I can fix the remaining points you shared.

**Comment by il-s** [comment]
#26 Add PR

**Comment by cssninjaStudio** [comment]
Thanks for your PR. I made changes to your PR to include what you've asked for. Please test and close the issue if you're ok with it.

**Comment by il-s** [comment]
Thank you very much! Everything works as it should.
