### ISSUE TITLE
font-awesome is outdated

### ISSUE THREAD

**Issue by diomed** [cssninjaStudio/fresh#5]
maybe you could even change it to v5

**Comment by cssninjaStudio** [comment]
Yes, I was thinking about trying the js injector from v5.

**Comment by diomed** [comment]
bulma is also 0.7.1. now

**Comment by cssninjaStudio** [comment]
it's built with a node-sass output of the bulma sass source. So it's just a matter of `npm install` to upgrade bulma.

**Comment by cssninjaStudio** [comment]
Will reopen a proper issue for Font Awesome 5+.
