### ISSUE TITLE
modals

### ISSUE THREAD

**Issue by diomed** [cssninjaStudio/fresh#6]
what do you think about adding some modals
that would be activated by clicking on colored buttons?

there is this [modal library](https://github.com/postare/bulma-modal-fx) 
but you could add any that you like, if you think it's a good idea. [I'm only suggesting 
that one coz of effects]

**Comment by cssninjaStudio** [comment]
Will consider it for a next release.

**Comment by cssninjaStudio** [comment]
Implemented in the new release.
