### ISSUE TITLE
Demo page: image pulled up too high, covering elements before it

### ISSUE THREAD

**Issue by melanieseltzer** [cssninjaStudio/fresh#7]
Not sure if this is isolated to the demo page or the actual codebase (I haven't used it yet), but I'm experiencing this in all browsers on my machine (iOS Chrome, Firefox, Safari).

## Issue definition

`.pushed-image` on the demo page has `margin-top: -29vh;` applied which is pulling it up too high, covering the content before it.

## Expected behavior

Is it supposed to look like this?

![expectedbehavior](https://user-images.githubusercontent.com/17421347/40744286-e989ff22-6408-11e8-838d-acea6101bd8b.jpg)

## Actual behavior

`margin-top: -29vh;` is always applied.

![actualbehavior](https://user-images.githubusercontent.com/17421347/40744292-eff1ce9e-6408-11e8-8afc-712945457fed.jpg)

## Steps to reproduce

Go to [Demo page](https://cssninjastudio.github.io/) and scroll down to `One Platform To rule them All` section.

**Comment by melanieseltzer** [comment]
I just realized there's a separate repo for that demo page, should I move this over there?

**Comment by cssninjaStudio** [comment]
Hello, may i know wich screen resolution you are using ? Posting this here is just fine.

**Comment by cssninjaStudio** [comment]
It seems this is happening under `1088px` screen resolutions. This can be fixed with a simple css media query : 

```
@media only screen and (max-device-width : 1087px) {
        img.pushed-image {
               margin-top: -12vh;
        }
}
```

**Comment by melanieseltzer** [comment]
Thanks for the reply! I have a large 27" widescreen monitor (resolution 2560 x 1440). Seems like it's actually an issue with the height and not width. Check out this gif - see how when you expand the height past a certain point it starts to overlap? I would think an issue with the `vh` unit.

![ezgif com-resize](https://user-images.githubusercontent.com/17421347/41061803-b49d845c-6988-11e8-8e89-4231aa22fc85.gif)

Not sure if device-width should be used anymore, since isn't it [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width)...

**Comment by cssninjaStudio** [comment]
Well I missed it by you are totally right. Since your display is really big, it is a vh problem. Try changing to a pixel or Rem Value instead of vh, it should do it.

**Comment by cssninjaStudio** [comment]
Fixed in new release.
