### ISSUE TITLE
what is this code for?

### ISSUE THREAD

**Issue by diomed** [cssninjaStudio/fresh#8]
https://github.com/cssninjaStudio/fresh/blob/b6155925bbc6e878f054e58cd0fcde5a30d21685/html/includes/sidebar.html#L8

forgive me if I'm mistaken, but looks like this chunk of code doesn't do anything much. 
maybe it was intended for some purpose never fulfilled.

Did you maybe plan to put this above, near the square icon?
That's the only place I could think this would go, and suit - 
of course, if properly styled.

Ah, I see now - this was meant to be single item - but there's no CSS for it yet.
so, this is kinda bug

**Comment by cssninjaStudio** [comment]
Got it, will take this in account for the next update.

**Comment by cssninjaStudio** [comment]
Non relevant anymore.
